---
title: Econ 57a  Environmental Economics
---

# Syllabus
Econ 57a, Environmental Economics, Fall 2021  
Lecture: Tuesday / Thursday 10:00-11:30 pm Eastern Standard Time (GMT -4)    
Location: TBD

**This is a tentative version of the syllabus, and is subject to change without prior notification.**

Instructor: Prof. Xinde "James" Ji   
Email: xji@brandeis.edu    
Office Hours: Wednesday 2:00 - 4:00 pm, or by appointment         

*Disclaimer: Email is the preferred communication mechanism, and I promise to respond to your email within 24 hours (48 hours on weekends). Using alternative communication media (instant messaging) does not guarantee a faster response.*     

Teaching Assistant: Ruoxi "Kathy" Zhang       
Email: ruoxizhang@brandeis.edu      
Office Hours: TBD       
Location: TBD  

Course materials will be posted on LATTE, as well as on my personal website, https://sites.google.com/site/xindejamesji/teaching/environmental-economics

## Teaching Modes
This class is taught **in person**. Attendance will not be tracked and you are not required to inform the instructor when you will miss a class. Please find out (either from the instructor or another student in the class) what you missed and get the relevant notes.

## Overview
How much is an endangered species worth? Are we going to run out of fuel in the next 50 years? How damaging is climate change, and how should we deal with it? Why are so many fisheries over-exploited, forests cut down, aquifers depleted, and are there ways to prevent that? 

Human society is intrinsically connected with nature. This course aims to provide an introduction to the economics regarding natural resources and the environment. In first part of the course, we will talk about how economists think about environmental and resource problems from methodological and analytical perspectives. Topics include market failures and policy instruments to correct them, property rights, and ways to evaluate benefits and costs of protecting the environment. In the second part of the course, we will dive into specific real-world environmental problems and analyze them using economic methods and tools. Topics will include non-renewable resources, air, water, climate, and others. 

## Learning goals
There are four learning goals that I hope you will be able to grasp by the end of this course. 

1. Know the facts (not the alternative facts or the rhetoric)
	* How damaging will climate change be on our society? 
	* How many jobs will be lost by phasing out fossil fuel in the next 10 years?
2. Know the concepts of which economists think of environmental problem
	* What is the Coase theorem?
	* What is scarcity rent?
3. Develop skills to think logically, critically, and coherently
	* Graphically show how to correct externalities using the instrument of taxation
	* Apply the equi-marginal principle to the case of freshwater allocation
4. Develop an economic mindset that can be applied to analyze real-world environmental problems
	* What are the trade-offs associated with protecting wildlife in Madagascar?
	* What is the best way to do so?

## Prerequisites
Students are expected to have knowledge of microeconomics at the level of Econ 2a (A Survey of Economics) or Econ 10a (Intro to Microeconomics). I will assume that you have basic knowledge regarding supply and demand, consumer and producer surplus, opportunity cost, etc. Please come to see me if you are not sure you meet the prerequisites of the course. 

## Textbook

**Required**    
`Markets and the Environment (2nd Edition), by Nathaniel Keohane and Sheila Olmstead, Island Press (2016)`    
The textbook is available for purchase at the Brandeis Bookstore. 

**Optional**   
`Environmental and Natural Resource Economics (11th Edition), by Tom Tietenberg and Lynne Lewis, Prentice Hall (2018)`    
`Economics and the Environment (7th Edition), by Eban Goodstein and Stephen Polasky, Wiley (2013)` 

**Readings**    
Additional readings will be posted on LATTE.  

## Grading
1. Thoughts and Questions (10%)   
A collection of readings will be assigned for each module. Please read them and reflect on the following question, unless otherwise specified:   
`What did you find most challenging, confusing, or noteworthy about the reading?`
	- You get 1 point for each TQ you submit as long as it is a good-faith effort. 
	- Each TQ is due by 10 pm on the day before we start a new module. 
	- I will drop the lowest two TQ scores.
2. Class Debate (20%)
	* See instruction below
3. Problem Sets (20%)	
	- There will be ~6 assignments throughout the semester. 
	- Problems will be posted on Tuesday, and are due on the next Tuesday before class (10 am). I accept late assignments, though it reduces your grade by 10% each day. 
	- All the assignments are individual unless otherwise stated. 
4. Midterm Exam (25%)
	* Time TBD
	* Open book, open notes
5. Final Exam (25%)
	* Time TBD
	* Open book, open notes
	* The exam will focus on the second half of the class, though you are expected to be able to apply concepts and tools covered in the first half of the class. 


## Instructions on Classroom Debate
You are expected to form a debate team of 3-4 students. There will be 4-5 debates throughout the semester, and you will be asked to choose one of the debate topics. Your stance on the question will be randomly drawn, one week before the debate. 

I will be moderating the debate, and the rest of the class will serve as the judge. The team that convince more people to change their stance wins the debate. The winning team will be rewarded by two extra points. In addition, the best debater (who may not necessarily come from the winning team) will get two extra points.

Here is a list of debate topics:

* Overpopulation is in conflict with the goal to develop sustainably.    
* Nuclear energy should power our future.    
* The Green New Deal is a policy that the United States should implement.   
* Developing nations should be given the opportunity to develop their economy first before cleaning up the environment.    
* We should make every effort to track and conserve our daily water use here in Waltham, MA. 

## Class Policies

#### Attendance
While participation in synchronous sessions is encouraged, there are no attendance requirements for this class. 

#### Academic Honesty
Every member of the University community is expected to maintain the highest standards of academic integrity. A student shall not submit work that is falsified or is not the result of the student's own effort. Infringement of academic honesty by a student subjects that student to serious penalties, which may include failure on the assignment, failure in the course, suspension from the University or other sanctions (see section 20 of Brandeis University Rights and Responsibilities). Please consult Brandeis University Rights and Responsibilities (see https://www.brandeis.edu/studentlife/srcs/rightsresponsibilities/index.html) for all policies and procedures related to academic integrity. Students may be required to submit work to TurnItIn.com software to verify originality. A student who is in course or assignment should consult the faculty member responsible for that course or assignment before submitting the work. Allegations of alleged academic dishonestry will be forwarded to the Department of Student Rights and Community Standards. Citation and research assistance can be found at Brandeis Library Guides - Citing Sources (https://guides.library.brandeis.edu/c.php?g=301723).

#### Accommodations   
Brandeis seeks to welcome and include all students. If you are a student who needs accommodations as outlined in an accommodations letter, please reach out me and present your letter of accommodation as soon as you can. I want to support you.

In order to provide test accommodations, I need the letter more than 48 hours in advance. I want to provide your accommodations, but cannot do so retroactively. If you have questions about documenting a disability or requesting accommodations, please contact Student Accessibility Support (SAS) at 781.736.3470 or access@brandeis.edu.

## Course Outline
*Note: the course outline is alive and breathing, so it may evolve spontaneously as the course goes along.*

1. Why Environmental Economics?
	* Why Adam Smith is not entirely correct
	* The need for environmental economics
	* The current state of business    
`Readings: Fullerton and Stavins (1998); Boyle and Kotchen (2018); McCarthy (2019)` 
2. The Efficiency Standard
	* The demand
	* The supply
	* The equi-marginal principle      
`Readings: Keohane and Olmstead Chapter 2 (pp 11-30); Do you think like an economist (LA Times)`
3. When Do Markets Fail
	* Externality
	* Property rights
	* The open-access problem
	* The public good problem    
`Readings: Keohane and Olmstead Chapter 5; Hardin(1968)`
4. How to Correct Market Failures
	* Command and control regulation
	* Pigovian taxes
	* Subsidies
	* Coase theorem, cap and trade
	* Policy instruments under uncertainty
	* Ostrom, common-pool resources   
`Readings: Keohane and Olmstead Chapter 8; Ronald Coase and the Misuse of Economics (New Yorker); Ostrom(2009)'s Nobel Prize Press Release`
5. Command-and-Control vs. Market-based Policy
	* Cost-effectiveness
	* Innovation
	* The US Sulfur Trading Scheme
	* Do we ever prefer command-and-control?    
`Readings: Keohane and Olmstead Chapter pp 168-184; Keohane and Olmstead pp 200-207; The Invisible Green Hand (The Economist)`
5. Measuring Benefits
	* Estimating causal effects
	* Estimating dollar values
	* stated preference
	* revealed preference    
`Readings: Goodstein and Polasky Chapter 5; EPA Plans to Revisit a Touchy Topic (New York Times)`    
**----Midterm about here----**    
6. Measuring Costs
	* Engineering vs. opportunity cost
	* Measuring social welfare losses
	* Who bears the cost?
	* Employment
	* Innovation    
`Readings: Keohane and Olmstead pp. 35-40, 43-44; Give me green, and jobs, but not green jobs (the Economist); Why Green Energy Can't Power a Job Engine (NYTimes)`   
7. Benefit-cost Analysis and Dynamic Efficiency
	* Criteria for evaluating programs
	* Discounting and present value
	* Dynamic decision-making
	* Decision under uncertainty    
`Readings: Keohane and Olmstead pp. 55-62; Goodstein and Polasky pp 146-150; Cunningham (2009)`
8. Non-renewable Resources
	* The two-period problem
	* The infinite horizon problem
	* Hotelling's rule
	* The Simon-Erhlich bet    
`Readings: Tietenberg and Lewis pp 107-116; Betting on the Planet (NYTimes)`
9. Water
	* Who owns the water?
	* The economics of water resources
	* Water transfers
	* When will we run out of water
`Readings: Tietenberg and Lewis pp 197-207; West's Drought and Growth Intensify Conflict Over Water Rights (NYTimes)`
11. Climate Change
	* The economic consequence of climate change
	* Measuring benefits and costs
	* Policy instruments: tax, cap, and the clean power plan
	* Global agreements
12. The Environment and Economic Development
	* Development and the environment
	* The Kuznets Hypothesis
	* Environmental governance and politics in the developing world




